# -*- coding: utf-8 -*-
"""Python Basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PRwFrjV5S_n4mVB3mUUYdAC08b16C6uT

print function
"""

print("Machine learning")

print("Machine Learning " + " prolect")

print(8)

print(8+3)

"""Basic data types:
1.Integer
2.Float
3.string
"""

type (5.3)

type("english")

"""Constants and Variables"""

super_hero="iron man"
print(super_hero)

marvel_superhero="CAPTAIN AMERICA"
print(marvel_superhero)

hero1,hero2,hero3="iron" , "captain america", "man"
print(hero1)
print(hero2)
print(hero3)

x= y = z =23
print(x)
print(y)
print(z)

"""Input function"""

number_1=int(input("Enter my first number:"))
number_2=int(input("Enter my second number:"))
sum=number_1+number_2
print(sum)

"""Changing data tye in python"""

num=5
float(num)
print(float(num))

"""Basic Data types in python
1.Integer
2.Floating Point
3.Complex
4.Boolean
5.String
"""

#integer
a=3
type(a)

#floating type
a=4.5
type(a)

#complex number
a=1 + 3j
print(a)
type(a)

#string
a="mim"
type(a)

"""Special data type
mutable obj
1.list
2.set
3.dictonary
"""

#list should be located in the square breacket
my_list=[1,2,3,4]
print(my_list)
type(my_list)

#list can have multiple data types
my_list=[2,3,1,8,"english",True]
my_list.append(8)
print(my_list)